# Generated by Django 2.1.7 on 2019-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_cross_one', models.CharField(max_length=255)),
                ('project_cross_two', models.CharField(max_length=255)),
                ('project_address', models.CharField(max_length=255)),
                ('project_city', models.CharField(max_length=255)),
                ('project_state', models.CharField(max_length=255)),
                ('project_zip', models.CharField(max_length=255)),
                ('project_submitter', models.CharField(max_length=255)),
                ('project_phone', models.CharField(max_length=255)),
                ('project_email', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
