# Generated by Django 2.1.7 on 2019-04-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_first_name', models.CharField(max_length=255)),
                ('adoption_last_name', models.CharField(max_length=255)),
                ('adoption_address', models.CharField(max_length=255)),
                ('adoption_city', models.CharField(max_length=255)),
                ('adoption_state', models.CharField(max_length=255)),
                ('adoption_zip', models.CharField(max_length=255)),
                ('adoption_phone', models.CharField(max_length=255)),
                ('adoption_email', models.CharField(max_length=255)),
                ('adoption_housing', models.CharField(max_length=255)),
                ('adoption_indoor_outdoor', models.CharField(max_length=255)),
                ('adoption_move', models.CharField(max_length=255)),
                ('adoption_why', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='cats.Cat')),
            ],
        ),
    ]
