# Generated by Django 2.1.7 on 2019-04-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
