# Generated by Django 2.1.7 on 2019-04-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='project_id',
            new_name='project',
        ),
    ]
